<?php

$q = array();

$q[] = 'CREATE TABLE `game`
        (
            `game_id` INT(11) PRIMARY KEY AUTO_INCREMENT,
            `game_bonus_home` INT(1) DEFAULT 1,
            `game_guest_auto` INT(1) DEFAULT 0,
            `game_guest_collision_1` INT(1) DEFAULT 0,
            `game_guest_collision_2` INT(1) DEFAULT 0,
            `game_guest_collision_3` INT(1) DEFAULT 0,
            `game_guest_forecast` INT(4) DEFAULT 0,
            `game_guest_mood_id` INT(1) DEFAULT 0,
            `game_guest_national_id` INT(5) DEFAULT 0,
            `game_guest_optimality_1` INT(3) DEFAULT 0,
            `game_guest_optimality_2` INT(3) DEFAULT 0,
            `game_guest_penalty` INT(2) DEFAULT 0,
            `game_guest_penalty_1` INT(2) DEFAULT 0,
            `game_guest_penalty_2` INT(2) DEFAULT 0,
            `game_guest_penalty_3` INT(2) DEFAULT 0,
            `game_guest_penalty_over` INT(2) DEFAULT 0,
            `game_guest_plus_minus` INT(1) DEFAULT 0,
            `game_guest_plus_minus_competition` DECIMAL(2,1) DEFAULT 0,
            `game_guest_plus_minus_mood` DECIMAL(2,1) DEFAULT 0,
            `game_guest_plus_minus_optimality_1` DECIMAL(2,1) DEFAULT 0,
            `game_guest_plus_minus_optimality_2` DECIMAL(3,1) DEFAULT 0,
            `game_guest_plus_minus_power` DECIMAL(2,1) DEFAULT 0,
            `game_guest_plus_minus_score` DECIMAL(2,1) DEFAULT 0,
            `game_guest_power` INT(4) DEFAULT 0,
            `game_guest_power_percent` INT(3) DEFAULT 0,
            `game_guest_rude_1_id` INT(1) DEFAULT 0,
            `game_guest_rude_2_id` INT(1) DEFAULT 0,
            `game_guest_rude_3_id` INT(1) DEFAULT 0,
            `game_guest_score` INT(2) DEFAULT 0,
            `game_guest_score_1` INT(2) DEFAULT 0,
            `game_guest_score_2` INT(2) DEFAULT 0,
            `game_guest_score_3` INT(2) DEFAULT 0,
            `game_guest_score_bullet` INT(1) DEFAULT 0,
            `game_guest_score_over` INT(1) DEFAULT 0,
            `game_guest_shot` INT(2) DEFAULT 0,
            `game_guest_shot_1` INT(2) DEFAULT 0,
            `game_guest_shot_2` INT(2) DEFAULT 0,
            `game_guest_shot_3` INT(2) DEFAULT 0,
            `game_guest_shot_over` INT(2) DEFAULT 0,
            `game_guest_style_1_id` INT(1) DEFAULT 0,
            `game_guest_style_2_id` INT(1) DEFAULT 0,
            `game_guest_style_3_id` INT(1) DEFAULT 0,
            `game_guest_tactic_1_id` INT(1) DEFAULT 0,
            `game_guest_tactic_2_id` INT(1) DEFAULT 0,
            `game_guest_tactic_3_id` INT(1) DEFAULT 0,
            `game_guest_team_id` INT(5) DEFAULT 0,
            `game_guest_teamwork_1` DOUBLE(4,2) DEFAULT 0,
            `game_guest_teamwork_2` DOUBLE(4,2) DEFAULT 0,
            `game_guest_teamwork_3` DOUBLE(4,2) DEFAULT 0,
            `game_home_auto` INT(0) DEFAULT 0,
            `game_home_collision_1` INT(1) DEFAULT 0,
            `game_home_collision_2` INT(1) DEFAULT 0,
            `game_home_collision_3` INT(1) DEFAULT 0,
            `game_home_forecast` INT(4) DEFAULT 0,
            `game_home_mood_id` INT(1) DEFAULT 0,
            `game_home_national_id` INT(5) DEFAULT 0,
            `game_home_optimality_1` INT(3) DEFAULT 0,
            `game_home_optimality_2` INT(3) DEFAULT 0,
            `game_home_penalty` INT(2) DEFAULT 0,
            `game_home_penalty_1` INT(2) DEFAULT 0,
            `game_home_penalty_2` INT(2) DEFAULT 0,
            `game_home_penalty_3` INT(2) DEFAULT 0,
            `game_home_penalty_over` INT(2) DEFAULT 0,
            `game_home_plus_minus` INT(1) DEFAULT 0,
            `game_home_plus_minus_competition` DECIMAL(2,1) DEFAULT 0,
            `game_home_plus_minus_mood` DECIMAL(2,1) DEFAULT 0,
            `game_home_plus_minus_optimality_1` DECIMAL(2,1) DEFAULT 0,
            `game_home_plus_minus_optimality_2` DECIMAL(3,1) DEFAULT 0,
            `game_home_plus_minus_power` DECIMAL(2,1) DEFAULT 0,
            `game_home_plus_minus_score` DECIMAL(2,1) DEFAULT 0,
            `game_home_power` INT(4) DEFAULT 0,
            `game_home_power_percent` INT(3) DEFAULT 0,
            `game_home_rude_1_id` INT(1) DEFAULT 0,
            `game_home_rude_2_id` INT(1) DEFAULT 0,
            `game_home_rude_3_id` INT(1) DEFAULT 0,
            `game_home_score` INT(2) DEFAULT 0,
            `game_home_score_1` INT(2) DEFAULT 0,
            `game_home_score_2` INT(2) DEFAULT 0,
            `game_home_score_3` INT(2) DEFAULT 0,
            `game_home_score_bullet` INT(1) DEFAULT 0,
            `game_home_score_over` INT(1) DEFAULT 0,
            `game_home_shot` INT(2) DEFAULT 0,
            `game_home_shot_1` INT(2) DEFAULT 0,
            `game_home_shot_2` INT(2) DEFAULT 0,
            `game_home_shot_3` INT(2) DEFAULT 0,
            `game_home_shot_over` INT(2) DEFAULT 0,
            `game_home_style_1_id` INT(1) DEFAULT 0,
            `game_home_style_2_id` INT(1) DEFAULT 0,
            `game_home_style_3_id` INT(1) DEFAULT 0,
            `game_home_tactic_1_id` INT(1) DEFAULT 0,
            `game_home_tactic_2_id` INT(1) DEFAULT 0,
            `game_home_tactic_3_id` INT(1) DEFAULT 0,
            `game_home_team_id` INT(5) DEFAULT 0,
            `game_home_teamwork_1` DOUBLE(4,2) DEFAULT 0,
            `game_home_teamwork_2` DOUBLE(4,2) DEFAULT 0,
            `game_home_teamwork_3` DOUBLE(4,2) DEFAULT 0,
            `game_played` INT(1) DEFAULT 0,
            `game_ticket` INT(2) DEFAULT 0,
            `game_schedule_id` INT(11) DEFAULT 0,
            `game_stadium_capacity` INT(5) DEFAULT 0,
            `game_stadium_id` INT(5) DEFAULT 0,
            `game_visitor` INT(5) DEFAULT 0
        );';
$q[] = 'CREATE INDEX `game_home_team_id` ON `game` (`game_home_team_id`);';
$q[] = 'CREATE INDEX `game_guest_team_id` ON `game` (`game_guest_team_id`);';
$q[] = 'CREATE INDEX `game_played` ON `game` (`game_played`);';
$q[] = 'CREATE INDEX `game_schedule_id` ON `game` (`game_schedule_id`);';