<?php

$q = array();

$q[] = 'CREATE TABLE `snapshot`
        (
            `snapshot_id` INT(11) PRIMARY KEY AUTO_INCREMENT,
            `snapshot_base` DECIMAL(4,2) DEFAULT 0,
            `snapshot_base_total` DECIMAL(4,2) DEFAULT 0,
            `snapshot_basemedical` DECIMAL(4,2) DEFAULT 0,
            `snapshot_basephisical` DECIMAL(4,2) DEFAULT 0,
            `snapshot_baseschool` DECIMAL(4,2) DEFAULT 0,
            `snapshot_basescout` DECIMAL(4,2) DEFAULT 0,
            `snapshot_basetraining` DECIMAL(4,2) DEFAULT 0,
            `snapshot_country` INT(3) DEFAULT 0,
            `snapshot_date` INT(11) DEFAULT 0,
            `snapshot_manager` INT(11) DEFAULT 0,
            `snapshot_manager_vip_percent` DECIMAL(5,2) DEFAULT 0,
            `snapshot_manager_with_team` INT(11) DEFAULT 0,
            `snapshot_player` INT(11) DEFAULT 0,
            `snapshot_player_age` DECIMAL(4,2) DEFAULT 0,
            `snapshot_player_c` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_gk` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_in_team` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_ld` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_lw` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_rd` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_rw` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_power` DECIMAL(6,2) DEFAULT 0,
            `snapshot_player_special_percent_no` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_one` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_two` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_three` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_four` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_athletic` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_combine` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_idol` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_leader` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_position` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_power` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_reaction` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_shot` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_speed` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_stick` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_special_percent_tackle` DECIMAL(5,2) DEFAULT 0,
            `snapshot_player_with_position_percent` DECIMAL(5,2) DEFAULT 0,
            `snapshot_season_id` INT(5) DEFAULT 0,
            `snapshot_team` INT(11) DEFAULT 0,
            `snapshot_team_finance` INT(11) DEFAULT 0,
            `snapshot_team_to_manager` DECIMAL(3,2) DEFAULT 0,
            `snapshot_stadium` INT(5) DEFAULT 0
        );';